json.DT_RowId customer_location.id
json.id customer_location.id
json.customer_id customer_location.customer_id
json.short_name customer_location.short_name
json.address_1 customer_location.address_1
json.address_2 customer_location.address_2
json.city customer_location.city
json.state customer_location.state
json.zip customer_location.zip
