admin = User.create(:email => 'admin@bcj.com', :first_name => "Josh", :last_name => "Goodbelly", :password => 'testeroo', :password_confirmation => 'testeroo', :roles => [:admin])
brewer = User.create(:email => 'brewer@bcj.com', :first_name => "Phil", :last_name => "Sunderson", :password => 'testeroo', :password_confirmation => 'testeroo', :roles => [:brewer])
sales = User.create(:email => 'sales@bcj.com', :first_name => "Tania", :last_name => "Tazmania", :password => 'testeroo', :password_confirmation => 'testeroo', :roles => [:sales])

cust1 = Customer.create(:name => 'test1', :user_id => 1, :distributor_id => 2, :price_tier_id => 1, :state => 0)
cust2 = Customer.create(:name => 'test2', :user_id => 1, :distributor_id => 2, :price_tier_id => 1, :state => 1)
cust3 = Customer.create(:name => 'test3', :user_id => 1, :distributor_id => 2, :price_tier_id => 1, :state => 2)
cust4 = Customer.create(:name => 'test4', :user_id => 1, :distributor_id => 2, :price_tier_id => 1, :state => 2)

cust1.customer_contacts.create(:primary => true, :first_name => "Jasper", :last_name => "Pipestone", :phone => "555-555-5555", :email => "jasper@banjofunk.com", :position => "banjo all day")
cust2.customer_contacts.create(:primary => true, :first_name => "Jasper", :last_name => "Pipestone", :phone => "555-555-5555", :email => "jasper@banjofunk.com", :position => "banjo all day")
cust3.customer_contacts.create(:primary => true, :first_name => "Jasper", :last_name => "Pipestone", :phone => "555-555-5555", :email => "jasper@banjofunk.com", :position => "banjo all day")
cust4.customer_contacts.create(:primary => true, :first_name => "Jasper", :last_name => "Pipestone", :phone => "555-555-5555", :email => "jasper@banjofunk.com", :position => "banjo all day")

cust1.customer_contacts.create(:primary => true, :first_name => "Julie", :last_name => "Pipestone", :phone => "777-777-7777", :email => "julie@banjofunk.com", :position => "banjo all day")
cust2.customer_contacts.create(:primary => true, :first_name => "Julie", :last_name => "Pipestone", :phone => "777-777-7777", :email => "julie@banjofunk.com", :position => "banjo all day")
cust3.customer_contacts.create(:primary => true, :first_name => "Julie", :last_name => "Pipestone", :phone => "777-777-7777", :email => "julie@banjofunk.com", :position => "banjo all day")
cust4.customer_contacts.create(:primary => true, :first_name => "Julie", :last_name => "Pipestone", :phone => "777-777-7777", :email => "julie@banjofunk.com", :position => "banjo all day")

cust1.customer_locations.create(:short_name => "Home", :address_1 => "2877 Shadow Creek Dr.", :address_2 => "#203", :city => "Boulder", :state => "CO", :zip => 80303)
cust2.customer_locations.create(:short_name => "Home", :address_1 => "2877 Shadow Creek Dr.", :address_2 => "#203", :city => "Boulder", :state => "CO", :zip => 80303)
cust3.customer_locations.create(:short_name => "Home", :address_1 => "2877 Shadow Creek Dr.", :address_2 => "#203", :city => "Boulder", :state => "CO", :zip => 80303)
cust4.customer_locations.create(:short_name => "Home", :address_1 => "2877 Shadow Creek Dr.", :address_2 => "#203", :city => "Boulder", :state => "CO", :zip => 80303)

cust1.customer_locations.create(:short_name => "Word", :address_1 => "3622 Walnut st", :address_2 => "", :city => "Boulder", :state => "CO", :zip => 80301)
cust2.customer_locations.create(:short_name => "Word", :address_1 => "3622 Walnut st", :address_2 => "", :city => "Boulder", :state => "CO", :zip => 80301)
cust3.customer_locations.create(:short_name => "Word", :address_1 => "3622 Walnut st", :address_2 => "", :city => "Boulder", :state => "CO", :zip => 80301)
cust4.customer_locations.create(:short_name => "Word", :address_1 => "3622 Walnut st", :address_2 => "", :city => "Boulder", :state => "CO", :zip => 80301)

cust1.customer_communications.create(:communication_type => 1, :communicated_with => "Carl", :notes => "Notes about a communication. lalala.")
cust2.customer_communications.create(:communication_type => 1, :communicated_with => "Carl", :notes => "Notes about a communication. lalala.")
cust3.customer_communications.create(:communication_type => 1, :communicated_with => "Carl", :notes => "Notes about a communication. lalala.")
cust4.customer_communications.create(:communication_type => 1, :communicated_with => "Carl", :notes => "Notes about a communication. lalala.")

cust1.customer_communications.create(:communication_type => 2, :communicated_with => "Steve", :notes => "Notes about a communication with steve. lalala.")
cust2.customer_communications.create(:communication_type => 2, :communicated_with => "Steve", :notes => "Notes about a communication with steve. lalala.")
cust3.customer_communications.create(:communication_type => 2, :communicated_with => "Steve", :notes => "Notes about a communication with steve. lalala.")
cust4.customer_communications.create(:communication_type => 2, :communicated_with => "Steve", :notes => "Notes about a communication with steve. lalala.")

cust1.customer_communications.create(:communication_type => 0, :communicated_with => "Fred", :notes => "Notes about a communication with Fred. lalala.")
cust2.customer_communications.create(:communication_type => 0, :communicated_with => "Fred", :notes => "Notes about a communication with Fred. lalala.")
cust3.customer_communications.create(:communication_type => 0, :communicated_with => "Fred", :notes => "Notes about a communication with Fred. lalala.")
cust4.customer_communications.create(:communication_type => 0, :communicated_with => "Fred", :notes => "Notes about a communication with Fred. lalala.")

cust1.comments.create(:user_id => admin.id, :text => "whats the status of this account?", :created_at => Time.current-21.days)
cust1.comments.create(:user_id => brewer.id, :text => "things are coming along. waiting to hear back from Carl.", :created_at => Time.current-12.days)
cust1.comments.create(:user_id => brewer.id, :text => "Awww Carl is the worst.", :created_at => Time.current-8.days)
cust1.comments.create(:user_id => admin.id, :text => "He's nice enough. I think itll be fine once we're in the system", :created_at => Time.current-7.days)
cust1.comments.create(:user_id => brewer.id, :text => "+1. Cant wait for this account", :created_at => Time.current-6.days)
cust1.comments.create(:user_id => sales.id, :text => "Good news! We're on the shelves!!")

cust2.comments.create(:user_id => admin.id, :text => "whats the status of this account?", :created_at => Time.current-21.days)
cust2.comments.create(:user_id => brewer.id, :text => "things are coming along. waiting to hear back from Carl.", :created_at => Time.current-12.days)
cust2.comments.create(:user_id => brewer.id, :text => "Awww Carl is the worst.", :created_at => Time.current-8.days)
cust2.comments.create(:user_id => admin.id, :text => "He's nice enough. I think itll be fine once we're in the system", :created_at => Time.current-7.days)
cust2.comments.create(:user_id => brewer.id, :text => "+1. Cant wait for this account", :created_at => Time.current-6.days)
cust2.comments.create(:user_id => sales.id, :text => "Good news! We're on the shelves!!")

cust3.comments.create(:user_id => admin.id, :text => "whats the status of this account?", :created_at => Time.current-21.days)
cust3.comments.create(:user_id => brewer.id, :text => "things are coming along. waiting to hear back from Carl.", :created_at => Time.current-12.days)
cust3.comments.create(:user_id => brewer.id, :text => "Awww Carl is the worst.", :created_at => Time.current-8.days)
cust3.comments.create(:user_id => admin.id, :text => "He's nice enough. I think itll be fine once we're in the system", :created_at => Time.current-7.days)
cust3.comments.create(:user_id => brewer.id, :text => "+1. Cant wait for this account", :created_at => Time.current-6.days)
cust3.comments.create(:user_id => sales.id, :text => "Good news! We're on the shelves!!")

cust4.comments.create(:user_id => admin.id, :text => "whats the status of this account?", :created_at => Time.current-21.days)
cust4.comments.create(:user_id => brewer.id, :text => "things are coming along. waiting to hear back from Carl.", :created_at => Time.current-12.days)
cust4.comments.create(:user_id => brewer.id, :text => "Awww Carl is the worst.", :created_at => Time.current-8.days)
cust4.comments.create(:user_id => admin.id, :text => "He's nice enough. I think itll be fine once we're in the system", :created_at => Time.current-7.days)
cust4.comments.create(:user_id => brewer.id, :text => "+1. Cant wait for this account", :created_at => Time.current-6.days)
cust4.comments.create(:user_id => sales.id, :text => "Good news! We're on the shelves!!")
